### ISSUE TITLE
AU Linux kernel autumn 2017 запрос на проверку mutex Бегунков

### ISSUE THREAD

**Issue by ISilence** [ISilence/au-linux-kernel-autumn-2017#5]
f7230a2730969791f212a7bca7b0bf125fe50f4b

**Comment by ISilence** [comment]
## quick reference

### structure: 

**group** represents per process mutex list.
device contains list of groups.

Mutex is represented by 2 structures:
1. **mutex_t**: userspace mutex
2. **struct ker_mutex**: kernel space mutex

**ker_mutex** contains pointer to **mutex_t**. The pointer remapped to kernel via **get_user_pages** + **vmap**. It's ugly, but creating **mutex_t** in kernel and mapping to userspace means messing up with vmas (we need some vma to use **remap_pfn_pages**).

### locking: 
1. 1 global lock -- protects list of groups
2. lock per group (protects mutex list of group)

To avoid deadlocks these locks are taken in direct order.

Mutex have shared semantic (ref count). Counter protected by another lock, which can be replaced by atomics). While destroying mutex should be accessible only by current thread & threads sleeping on the mutexs' wait_queue.

### tests:
1 thread:  
this impl have the similar time with pthread.  

10^5 threads:  
this impl takes comparable amount of time with bare syscalls (ioctls without any code). (pthread mutexes are faster)

**Comment by eabatalov** [comment]
Looks perfect! Thank you. 100% for the task.
